name: Sayan Action BOT

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-text:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config --global user.name "Prime-Sonu"
          git config --global user.email "247044568+Prime-Sonu@users.noreply.github.com"

      - name: Sync and Update Log
        run: |
          export TZ="Asia/Kolkata"
          git pull origin main --rebase
          
          echo "✨ Profile Active | IST: $(date +'%Y-%m-%d %H:%M:%S') | Session: $RANDOM" >> activity.txt



          git add activity.txt
          git commit -m "Activity Log Updated ✅ [$(date +'%d-%m-%Y %H:%M')] #$RANDOM" --allow-empty
          git push origin main
          
